### ISSUE TITLE
[FEAT] 여행 프로그램 상세 페이지 구현

### ISSUE THREAD

**Issue by AAminha** [Kusitms-28th-Meet-Up-B/Frontend#17]
## Issue Perposal

여행 프로그램 상세 페이지 구현

## Branch Name

생성 브랜치 이름: `feature/#17/detail`

## To-do List

- [x] 여행 프로그램 대표 정보
  - [x] 포스터 이미지
  - [x] 남은 날짜 / 제목 / 지역, 모집 기간, 여행 기간, 문의처, 지역
  - [x] 좋아요 버튼
  - [x] 신청링크 버튼
- [x] 여행 프로그램 상세 정보
- [x] 유사 지원 사업 추천
  - [x] 여행 프로그램 목록 (컴포넌트 활용)
- [x] '지원 쿨팁 보기>' 플로팅 버튼
