### ISSUE TITLE
[FEAT] 검색 페이지 구현

### ISSUE THREAD

**Issue by AAminha** [Kusitms-28th-Meet-Up-B/Frontend#5]
## Issue Perposal

검색 페이지 구현

## Branch Name

생성 브랜치 이름: `feature/#5/search`

## To-do List

- [x] 검색바
- [x] 검색 필터링
  - [x] 정렬 (최신순, 인기순, 빠른 마감 순, 늦은 마감 순)
  - [x] 지역 (전국, 수도권, 충청도, 전라도, 강원도, 경상도, 제주도)
  - [x] 여행 프로그램 (전체, 여행지원사업, 여행 공모전, 여행 대외활동)
  - [x] 세부 카테고리
  - [x] 모집 기간 (달력으로 표시)
  - [x] 여행 기간 (달력으로 표시)
  - [x] 선택 버튼
- [x] 검색 결과
  - [x] `[지역명] [여행 프로그램 종류] [결과 개수]건`
  - [x] #18
  - [x] 지도에서 보기 버튼
