### ISSUE TITLE
[FEAT] 프로그램 상세 페이지 추가 항목 구현

### ISSUE THREAD

**Issue by AAminha** [Kusitms-28th-Meet-Up-B/Frontend#52]
## Issue Perposal

 프로그램 상세 페이지 추가 항목 구현

## Branch Name

생성 브랜치 이름: `feature/#52/detailProgram`

## To-do List

- [x] ProgramCard 수정
  - [x] ProgramCardItem에 LikeButton 컴포넌트 적용
  - [x] 이미지가 없는 프로그램의 경우 디폴트 이미지 삽입
- [ ] DetailProgram 수정 및 추가
  - [x] LikeButton 컴포넌트 적용
  - [x] 이미지가 없는 프로그램의 경우 디폴트 이미지 삽입
  - [x] 배경색 일부분 다르게 구현
  - [x] 유사한 프로그램 추천 API 연결
  - [x] 숙소 추천 UI 및 API 연결
  - [x] 여행지 추천 UI 및 API 연결
  - [ ] 꿀팁 버튼 수정
  - [x] 신청 링크 다시 구현
  - [x] 해당 프로그램 공고 작성자의 경우 수정, 삭제 버튼 보이도록
